server:
  port: 9090


spring:
  datasource:
    url: jdbc:mysql://192.168.11.142:3306/deji_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
